services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: framework-approach:py3119
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: sleep infinity
