from __future__ import annotations

import argparse
from pathlib import Path


def _build_manifest(workspace_root: Path) -> str:
    templates_dir = workspace_root / "tools" / "model_templates"
    docs_models_dir = workspace_root / "docs" / "models"

    template_paths = sorted(templates_dir.glob("*_template.py"))
    doc_paths = sorted(docs_models_dir.glob("*.md"))

    docs_by_stem = {path.stem: path for path in doc_paths}
    matched_doc_stems: set[str] = set()

    lines: list[str] = [
        "# Template to Docs Manifest",
        "",
        "This file is generated by `tools/generate_template_docs_manifest.py`.",
        "Run with `--check` in CI to detect documentation drift.",
        "",
        "## Coverage",
        "",
        "| Template | Expected Doc | Status |",
        "|---|---|---|",
    ]

    for template_path in template_paths:
        template_stem = template_path.stem
        doc_stem = template_stem.removesuffix("_template")
        expected_doc = docs_by_stem.get(doc_stem)
        status = "✅ linked" if expected_doc else "❌ missing"
        if expected_doc:
            matched_doc_stems.add(doc_stem)
            doc_display = f"[docs/models/{expected_doc.name}](../models/{expected_doc.name})"
        else:
            doc_display = f"docs/models/{doc_stem}.md"
        template_display = f"[tools/model_templates/{template_path.name}](../../tools/model_templates/{template_path.name})"
        lines.append(f"| {template_display} | {doc_display} | {status} |")

    orphan_docs = [path for path in doc_paths if path.stem not in matched_doc_stems]

    lines.extend([
        "",
        "## Orphan Docs",
        "",
    ])

    if orphan_docs:
        for doc_path in orphan_docs:
            lines.append(f"- [docs/models/{doc_path.name}](../models/{doc_path.name})")
    else:
        lines.append("- None")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate template-doc coverage manifest")
    parser.add_argument("--check", action="store_true", help="Exit non-zero when manifest is out of date")
    args = parser.parse_args()

    workspace_root = Path(__file__).resolve().parents[1]
    manifest_path = workspace_root / "docs" / "workflows" / "template_docs_manifest.md"
    expected_content = _build_manifest(workspace_root)

    if args.check:
        if not manifest_path.exists():
            print(f"Missing manifest: {manifest_path}")
            return 1
        current_content = manifest_path.read_text(encoding="utf-8")
        if current_content != expected_content:
            print("Manifest drift detected. Run: python tools/generate_template_docs_manifest.py")
            return 1
        print("Manifest is up to date.")
        return 0

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(expected_content, encoding="utf-8")
    print(f"Wrote {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
